make better use of systemd logging mechanics

diff --git a/zram-config b/zram-config
--- a/zram-config
+++ b/zram-config
@@ -1,24 +1,27 @@
 #!/usr/bin/env bash
 
-timestamp() { printf "%(%FT%T%z)T\\n" "-1"; }
+DBG="<7>D"
+INF="<6>I"
+WRN="<4>W"
+ERR="<3>E"
 
 log() {
   local log_level="$1"
   local log_message="$2"
-  if [[ $log_level != "ERR" ]]; then
-    echo "$(timestamp) | $log_level | ${FUNCNAME[1]}: $log_message"
+  if [[ $log_level != "$ERR" ]]; then
+    echo "$log_level ${FUNCNAME[1]}: $log_message"
   else
-    echo "$(timestamp) | $log_level | ${FUNCNAME[1]}: $log_message Exiting!" >&2
+    echo "$log_level ${FUNCNAME[1]}: $log_message Exiting!" >&2
   fi
 }
 
 createZdevice() {
   local retVal=0
 
-  log "INF" "Beginning creation of zram device."
+  log "$DBG" "Beginning creation of zram device."
   if ! [[ -d "/sys/class/zram-control" ]]; then
     if ! modprobe zram num_devices=0 &> /dev/null; then
-      log "ERR" "Failed to load zram module."
+      log "$ERR" "Failed to load zram module."
       return 1
     fi
   fi
@@ -26,24 +29,24 @@ createZdevice() {
   RAM_DEV="$(cat /sys/class/zram-control/hot_add)"
 
   if [[ -z $RAM_DEV ]]; then
-    log "WRN" "Failed to find an open zram device, trying one more time."
+    log "$WRN" "Failed to find an open zram device, trying one more time."
     RAM_DEV="$(cat /sys/class/zram-control/hot_add)"
     if [[ -z $RAM_DEV ]]; then
-      log "ERR" "Failed to find an open zram device."
+      log "$ERR" "Failed to find an open zram device."
       return 1
     fi
   fi
 
   if ! echo "$ALG" > "/sys/block/zram${RAM_DEV}/comp_algorithm"; then
-    log "ERR" "Failed to set compression algorithm for /dev/zram${RAM_DEV}."
+    log "$ERR" "Failed to set compression algorithm for /dev/zram${RAM_DEV}."
     retVal=1
   fi
   if ! echo "$DISK_SIZE" > "/sys/block/zram${RAM_DEV}/disksize"; then
-    log "ERR" "Failed to set disk size for /dev/zram${RAM_DEV}."
+    log "$ERR" "Failed to set disk size for /dev/zram${RAM_DEV}."
     retVal=1
   fi
   if ! echo "$MEM_SIZE" > "/sys/block/zram${RAM_DEV}/mem_limit"; then
-    log "ERR" "Failed to set memory limit for /dev/zram${RAM_DEV}."
+    log "$ERR" "Failed to set memory limit for /dev/zram${RAM_DEV}."
     retVal=1
   fi
   if [[ $retVal -ne 0 ]]; then
@@ -53,50 +56,50 @@ createZdevice() {
   fi
 
   if [[ $MEM_SIZE == 0 ]]; then
-    log "INF" "No memory limit set for /dev/zram${RAM_DEV}."
+    log "$INF" "No memory limit set for /dev/zram${RAM_DEV}."
   fi
 
-  log "INF" "zram${RAM_DEV} created comp_algorithm=${ALG} mem_limit=${MEM_SIZE} disksize=${DISK_SIZE}."
+  log "$INF" "zram${RAM_DEV} created comp_algorithm=${ALG} mem_limit=${MEM_SIZE} disksize=${DISK_SIZE}."
 }
 
 createZswap() {
-  log "INF" "Beginning creation of swap device."
+  log "$DBG" "Beginning creation of swap device."
   createZdevice || return 1
   if ! mkswap --label "zram-config${RAM_DEV}" "/dev/zram${RAM_DEV}" &> /dev/null; then
-    log "ERR" "Failed to create swap on /dev/zram${RAM_DEV}."
+    log "$ERR" "Failed to create swap on /dev/zram${RAM_DEV}."
     return 1
   fi
 
   if [[ -n $PRIORITY ]]; then
     if ! swapon -p "$PRIORITY" "/dev/zram${RAM_DEV}" &> /dev/null; then
-      log "ERR" "Failed to swapon on /dev/zram${RAM_DEV}."
+      log "$ERR" "Failed to swapon on /dev/zram${RAM_DEV}."
       return 1
     fi
   else
-    log "ERR" "No swap priority provided for /dev/zram${RAM_DEV}."
+    log "$ERR" "No swap priority provided for /dev/zram${RAM_DEV}."
     return 1
   fi
 
   if [[ -n $PAGE_CLUSTER ]]; then
     if ! sysctl vm.page-cluster="$PAGE_CLUSTER"; then
-      log "ERR" "Failed to set page_cluster for /dev/zram${RAM_DEV}."
+      log "$ERR" "Failed to set page_cluster for /dev/zram${RAM_DEV}."
       return 1
     fi
   else
-    log "INF" "No page cluster provided for /dev/zram${RAM_DEV}."
+    log "$INF" "No page cluster provided for /dev/zram${RAM_DEV}."
   fi
 
   if [[ -n $SWAPPINESS ]]; then
     if ! sysctl vm.swappiness="$SWAPPINESS"; then
-      log "ERR" "Failed to set swappiness for /dev/zram${RAM_DEV}."
+      log "$ERR" "Failed to set swappiness for /dev/zram${RAM_DEV}."
       return 1
     fi
   else
-    log "INF" "No swappiness provided for /dev/zram${RAM_DEV}."
+    log "$INF" "No swappiness provided for /dev/zram${RAM_DEV}."
   fi
 
   echo "swap    zram${RAM_DEV}" >> "$ZDIR"/zram-device-list
-  log "INF" "Completed swap device creation."
+  log "$INF" "Completed swap device creation."
 }
 
 createZdir() {
@@ -107,12 +110,12 @@ createZdir() {
   local dirFSType
   local retVal=0
 
-  log "INF" "Beginning creation of ${ZBIND}/zram${RAM_DEV}."
+  log "$DBG" "Beginning creation of ${ZBIND}/zram${RAM_DEV}."
   if [[ -z $BIND_DIR ]]; then
-    log "ERR" "No bind directory provided in '/etc/ztab'."
+    log "$ERR" "No bind directory provided in '/etc/ztab'."
     return 1
   elif [[ -z $TARGET_DIR ]]; then
-    log "ERR" "No mount directory provided in '/etc/ztab'."
+    log "$ERR" "No mount directory provided in '/etc/ztab'."
     return 1
   fi
 
@@ -121,26 +124,26 @@ createZdir() {
   dirPerm="$(stat -c "%a" "$TARGET_DIR")"
   dirUser="$(stat -c "%u" "$TARGET_DIR")"
   dirGroup="$(stat -c "%g" "$TARGET_DIR")"
-  log "DBG" "File permissions for $TARGET_DIR - $dirPerm ${dirUser}:${dirGroup}"
+  log "$DBG" "File permissions for $TARGET_DIR - $dirPerm ${dirUser}:${dirGroup}"
 
   if ! mount --bind "${TARGET_DIR}/" "${ZBIND}/${BIND_DIR}/" &> /dev/null; then
-    log "ERR" "Failed to bind mount ${TARGET_DIR} to ${ZBIND}/${BIND_DIR}."
+    log "$ERR" "Failed to bind mount ${TARGET_DIR} to ${ZBIND}/${BIND_DIR}."
     return 1
   fi
   if ! mount --make-private "${ZBIND}/${BIND_DIR}/" &> /dev/null; then
-    log "ERR" "Failed to make ${ZBIND}/${BIND_DIR} private."
+    log "$ERR" "Failed to make ${ZBIND}/${BIND_DIR} private."
     return 1
   fi
 
   dirMountOpt="$(awk -v a="${ZBIND}/${BIND_DIR}" '$2 == a {print $4}' /proc/mounts | head -1)"
   dirFSType="$(awk -v a="${ZBIND}/${BIND_DIR}" '$2 == a {print $3}' /proc/mounts | head -1)"
-  log "DBG" "Directory settings - ${dirMountOpt} ${dirFSType}."
+  log "$DBG" "Directory settings - ${dirMountOpt} ${dirFSType}."
 
   createZdevice || return 1
 
   # shellcheck disable=SC2086
   if ! ([[ -x $(command -v mkfs.$dirFSType) ]] && mkfs.$dirFSType "/dev/zram${RAM_DEV}" &> /dev/null); then
-    log "ERR" "Failed to create filesystem on /dev/zram${RAM_DEV}."
+    log "$ERR" "Failed to create filesystem on /dev/zram${RAM_DEV}."
     return 1
   fi
   mkdir -p "${ZBIND}/zram${RAM_DEV}"
@@ -150,7 +153,7 @@ createZdir() {
   chown "${dirUser}:${dirGroup}" "${ZBIND}/zram${RAM_DEV}/upper" "${ZBIND}/zram${RAM_DEV}/workdir" "$TARGET_DIR" &> /dev/null || retVal=1
   chmod "$dirPerm" "${ZBIND}/zram${RAM_DEV}/upper" "${ZBIND}/zram${RAM_DEV}/workdir" "$TARGET_DIR" &> /dev/null || retVal=1
   if [[ $retVal -ne 0 ]]; then
-    log "ERR" "Failed to setup and mount ${ZBIND}/zram${RAM_DEV}."
+    log "$ERR" "Failed to setup and mount ${ZBIND}/zram${RAM_DEV}."
     return 1
   fi
 
@@ -159,60 +162,62 @@ createZdir() {
   if [[ $ZTYPE == "log" ]] && [[ -n $OLDLOG_DIR ]]; then
     echo -e "olddir ${OLDLOG_DIR}\\ncreateolddir 755 root root\\nrenamecopy" > /etc/logrotate.d/00_oldlog
   elif [[ $ZTYPE == "log" ]]; then
-    log "INF" "No oldlog directory provided, skipping oldlog configuration."
+    log "$INF" "No oldlog directory provided, skipping oldlog configuration."
   fi
-  log "INF" "Creation of ${ZBIND}/zram${RAM_DEV} complete."
+  log "$INF" "Creation of ${ZBIND}/zram${RAM_DEV} complete."
 }
 
 mergeOverlay() {
-  log "INF" "Beginning merge of ${ZBIND}/${BIND_DIR}."
-  if ! overlay merge --force-execution --ignore-mounted --lowerdir="${ZBIND}/${BIND_DIR}" --upperdir="${ZBIND}/${ZRAM_DEV}/upper" &> /dev/null; then
-    log "ERR" "Failed to merge ${ZBIND}/${BIND_DIR}."
-    return 1
+  log "$DBG" "Beginning merge of ${ZBIND}/${BIND_DIR}."
+  overlay merge --force-execution --ignore-mounted --lowerdir="${ZBIND}/${BIND_DIR}" --upperdir="${ZBIND}/${ZRAM_DEV}/upper"
+  local status=$?
+  if [ $status -ne 0 ]; then
+    log "$ERR" "Failed to merge ${ZBIND}/${BIND_DIR}. Exit status: $status"
+    return $status
   fi
-  log "INF" "Merge of ${ZBIND}/${BIND_DIR} complete."
+  log "$INF" "Merge of ${ZBIND}/${BIND_DIR} complete."
 }
 
 removeZdevice() {
   local count=0
 
-  log "INF" "Beginning removal of device /dev/${ZRAM_DEV}."
+  log "$DBG" "Beginning removal of device /dev/${ZRAM_DEV}."
 
   if [[ -z $ZRAM_DEV ]]; then
-    log "ERR" "Failed to remove zram device, missing required variables."
+    log "$ERR" "Failed to remove zram device, missing required variables."
     return 1
   fi
 
   if [[ -z $SHUTDOWN ]]; then  # We don't care about device reset when shutting down system
     until echo 1 > "/sys/block/${ZRAM_DEV}/reset"; do
       if [[ $count -ge 5 ]]; then
-        log "WRN" "Failed to reset zram device, attempting to remove it anyways."
+        log "$WRN" "Failed to reset zram device, attempting to remove it anyways."
         break
       fi
-      log "WRN" "Failed to reset zram device, trying again in 5 seconds."
+      log "$WRN" "Failed to reset zram device, trying again in 5 seconds."
       count=$(( count + 1 ))
       sleep 5
     done
     count=0
     until echo "${ZRAM_DEV//[!0-9]/}" > /sys/class/zram-control/hot_remove; do
       if [[ $count -ge 5 ]]; then
-        log "WRN" "Failed to remove zram device, consider rebooting to reset zram devices."
+        log "$WRN" "Failed to remove zram device, consider rebooting to reset zram devices."
         break
       fi
-      log "WRN" "Failed to remove zram device, trying again in 5 seconds."
+      log "$WRN" "Failed to remove zram device, trying again in 5 seconds."
       count=$(( count + 1 ))
       sleep 5
     done
   fi
 
-  log "INF" "Completed removal of device /dev/${ZRAM_DEV}."
+  log "$INF" "Completed removal of device /dev/${ZRAM_DEV}."
 }
 
 umountTarget() {
   if ! umount "$1/" &> /dev/null; then
-    log "WRN" "Failed to umount $1, trying one more time lazily."
+    log "$WRN" "Failed to umount $1, trying one more time lazily."
     if ! umount --lazy "$1/" &> /dev/null; then
-      log "ERR" "Failed to umount $1."
+      log "$ERR" "Failed to umount $1."
       return 1
     fi
   fi
@@ -221,14 +226,14 @@ umountTarget() {
 removeZdir() {
   local retVal=0
 
-  log "INF" "Beginning merge of device /dev/${ZRAM_DEV}."
+  log "$DBG" "Beginning merge of device /dev/${ZRAM_DEV}."
 
   [[ -n $OLDLOG_DIR ]] && rm -f /etc/logrotate.d/00_oldlog
   [[ -z $TARGET_DIR ]] && retVal=1
   [[ -z $ZRAM_DEV ]] && retVal=1
   [[ -z $BIND_DIR ]] && retVal=1
   if [[ $retVal -ne 0 ]]; then
-    log "ERR" "Failed to remove zram device, missing required variables."
+    log "$ERR" "Failed to remove zram device, missing required variables."
     return 1
   fi
 
@@ -242,26 +247,26 @@ removeZdir() {
   umountTarget "${ZBIND}/${BIND_DIR}" || return 1
   rm -rf "${ZBIND:?}/${BIND_DIR}"
 
-  log "INF" "Completed merge of device /dev/${ZRAM_DEV}."
+  log "$INF" "Completed merge of device /dev/${ZRAM_DEV}."
 
   removeZdevice || return 1
 }
 
 removeZswap() {
-  log "INF" "Beginning removal of swap device."
+  log "$DBG" "Beginning removal of swap device."
 
   if [[ -z $SHUTDOWN ]] && ! swapoff "/dev/${ZRAM_DEV}" &> /dev/null; then
-    log "ERR" "Failed to swapoff /dev/${ZRAM_DEV}."
+    log "$ERR" "Failed to swapoff /dev/${ZRAM_DEV}."
     return 1
   fi
 
-  log "INF" "Completed swap device removal."
+  log "$INF" "Completed swap device removal."
 
   removeZdevice || return 1
 }
 
 syncZdir() {
-  log "INF" "Beginning sync of device /dev/${ZRAM_DEV}."
+  log "$DBG" "Beginning sync of device /dev/${ZRAM_DEV}."
 
   umountTarget "$TARGET_DIR" || return 1
 
@@ -269,21 +274,21 @@ syncZdir() {
 
   mkdir -p "${ZBIND}/${ZRAM_DEV}/upper" "${ZBIND}/${ZRAM_DEV}/workdir" "$TARGET_DIR"
   if ! mount --types overlay -o "redirect_dir=on,lowerdir=${ZBIND}/${BIND_DIR},upperdir=${ZBIND}/${ZRAM_DEV}/upper,workdir=${ZBIND}/${ZRAM_DEV}/workdir" "overlay${ZRAM_DEV//[!0-9]/}" "$TARGET_DIR" &> /dev/null; then
-    log "ERR" "Failed to remount overlay for ${ZBIND}/${BIND_DIR}."
+    log "$ERR" "Failed to remount overlay for ${ZBIND}/${BIND_DIR}."
     return 1
   fi
 
-  log "INF" "Completed sync of device /dev/${ZRAM_DEV}."
+  log "$INF" "Completed sync of device /dev/${ZRAM_DEV}."
 }
 
 serviceConfiguration() {
   if [[ $1 == "stop" ]]; then
-    log "INF" "Stopping services that interfere with zram device configuration."
+    log "$DBG" "Stopping services that interfere with zram device configuration."
     if [[ $OS == "alpine" ]]; then
       if rc-service syslog status &> /dev/null; then
         export syslogActiveAlpine="true"
         if ! rc-service syslog stop; then
-          log "ERR" "Failed to stop syslog service."
+          log "$ERR" "Failed to stop syslog service."
           return 1
         fi
       fi
@@ -291,39 +296,39 @@ serviceConfiguration() {
       if [[ $(systemctl is-active rsyslog.service) == "active" ]]; then
         export rsyslogActive="true"
         if ! systemctl --no-block stop syslog.socket; then
-          log "ERR" "Failed to stop syslog service."
+          log "$ERR" "Failed to stop syslog service."
           return 1
         fi
       fi
       if [[ $(systemctl is-active systemd-journald.service) == "active" ]]; then
         export journaldActive="true"
         if ! journalctl --flush; then
-          log "ERR" "Failed to flush journal."
+          log "$ERR" "Failed to flush journal."
           return 1
         fi
         if ! systemctl --no-block stop systemd-journald.socket systemd-journald-audit.socket systemd-journald-dev-log.socket; then
-          log "ERR" "Failed to stop journald service."
+          log "$ERR" "Failed to stop journald service."
           return 1
         fi
       fi
     fi
   elif [[ $1 == "start" ]]; then
-    log "INF" "Restarting services that interfere with zram device configuration."
+    log "$DBG" "Restarting services that interfere with zram device configuration."
     if [[ -n $journaldActive ]]; then
       if ! systemctl --no-block restart systemd-journald.socket systemd-journald-audit.socket systemd-journald-dev-log.socket; then
-        log "ERR" "Failed to restart journald service."
+        log "$ERR" "Failed to restart journald service."
         return 1
       fi
     fi
     if [[ -n $rsyslogActive ]]; then
       if ! systemctl --no-block restart syslog.socket; then
-        log "ERR" "Failed to restart syslog service."
+        log "$ERR" "Failed to restart syslog service."
         return 1
       fi
     fi
     if [[ -n $syslogActiveAlpine ]]; then
       if ! rc-service syslog start; then
-        log "ERR" "Failed to start syslog service."
+        log "$ERR" "Failed to start syslog service."
         return 1
       fi
     fi
@@ -345,7 +350,7 @@ sed -i -E 's/(\tbind_dir|\t\/\w*\.bind)//g' /etc/ztab
 
 case "$1" in
   start)
-    log "INF" "Starting services."
+    log "$DBG" "Starting services."
     ZTAB_EMPTY="true"
     while read -r line; do
       case "$line" in
@@ -374,7 +379,7 @@ case "$1" in
               entry="$(grep "${1}.*${5}" "$ZDIR"/zram-device-list)"
             fi
             if [[ -n $entry ]]; then
-              log "WRN" "Entry ${entry} already exists as a zram device, skipping recreation of device."
+              log "$WRN" "Entry ${entry} already exists as a zram device, skipping recreation of device."
               continue
             fi
           fi
@@ -399,15 +404,15 @@ case "$1" in
       esac
     done < /etc/ztab
     if [[ $ZTAB_EMPTY == "true" ]]; then
-      log "ERR" "Cannot begin start, '/etc/ztab' is empty and needs to be configured."
+      log "$ERR" "Cannot begin start, '/etc/ztab' is empty and needs to be configured."
       exit 1
     fi
     ;;
 
   stop)
-    log "INF" "Stopping services."
+    log "$DBG" "Stopping services."
     if ! [[ -s "$ZDIR"/zram-device-list ]]; then
-      log "WRN" "Skipping stop, zram-config not running."
+      log "$WRN" "Skipping stop, zram-config not running."
       exit 0
     fi
     tac "$ZDIR"/zram-device-list > "$ZDIR"/zram-device-list.rev
@@ -447,9 +452,9 @@ case "$1" in
     ;;
 
   sync)
-    log "INF" "Syncing files."
+    log "$DBG" "Syncing files."
     if ! [[ -s "$ZDIR"/zram-device-list ]]; then
-      log "WRN" "Skipping sync, zram-config not running."
+      log "$WRN" "Skipping sync, zram-config not running."
       exit 0
     fi
     if [[ $# -gt 1 ]]; then
